# Generated by Django 5.2.1 on 2025-06-04 23:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('departments', '0001_initial'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=70, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=70, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener 8 dígitos numéricos.', regex='^\\d{8}$')], verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('email_personal', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Personal')),
                ('email_empresa', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Empresa')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('codigo_empleado', models.CharField(max_length=20, unique=True, verbose_name='Código de Empleado')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('salario_actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario Actual')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='employee/fotos/', verbose_name='Foto')),
                ('firma', models.ImageField(blank=True, null=True, upload_to='employee/firmas/', verbose_name='Firma')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_cese', models.DateField(blank=True, null=True, verbose_name='Fecha de Cese')),
                ('motivo_cese', models.TextField(blank=True, null=True, verbose_name='Motivo de Cese')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='positions.position', verbose_name='Cargo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombres', 'apellidos'],
                'unique_together': {('empresa', 'codigo_empleado')},
            },
        ),
    ]
