# Generated by Django 5.2.1 on 2025-06-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email_empresa',
        ),
        migrations.AddField(
            model_name='employee',
            name='rest_day',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], default='domingo', max_length=20, verbose_name='Día de Descanso'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_type',
            field=models.CharField(choices=[('turno_1', 'Turno 1'), ('turno_2', 'Turno 2'), ('turno_3', 'Turno 3'), ('turno_4', 'Turno 4')], default='turno_1', max_length=20, verbose_name='Tipo de Turno'),
        ),
    ]
