# Generated by Django 5.2.1 on 2025-06-05 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Feriado')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('nacional', 'Feriado Nacional'), ('local', 'Feriado Local'), ('empresa', 'Día de la Empresa'), ('religioso', 'Feriado Religioso')], default='nacional', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('eobligatorio', models.BooleanField(default=True, verbose_name='Es Obligatorio')),
                ('es_global', models.BooleanField(default=True, verbose_name='Aplica a Todas las Empresas')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['fecha'],
                'unique_together': {('fecha', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='HolidayCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feriados_especificos', to='companies.company')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_especificas', to='holidays.holiday')),
            ],
            options={
                'verbose_name': 'Feriado por Empresa',
                'verbose_name_plural': 'Feriados por Empresa',
                'unique_together': {('holiday', 'company')},
            },
        ),
    ]
