# Generated by Django 5.2.1 on 2025-06-04 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('salario_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario Mínimo')),
                ('salario_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario Máximo')),
                ('titulo', models.BooleanField(default=False, verbose_name='Requiere Título')),
                ('experiencia', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Experiencia Requerida')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('cargo_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='positions.position', verbose_name='Cargo Superior')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['empresa', 'departamento', 'nombre'],
                'unique_together': {('departamento', 'codigo')},
            },
        ),
    ]
