# Generated by Django 5.2.1 on 2025-06-05 04:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0002_remove_employee_email_empresa_employee_rest_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10, verbose_name='Tipo de Marcación')),
                ('metodo', models.CharField(choices=[('qr_movil', 'QR desde Móvil'), ('manual_seguridad', 'Manual desde Seguridad'), ('web_admin', 'Web Admin')], default='qr_movil', max_length=20, verbose_name='Método de Marcación')),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitud')),
                ('dispositivo_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Info del Dispositivo')),
                ('registrado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registrado por')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Marcación de Asistencia',
                'verbose_name_plural': 'Marcaciones de Asistencia',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Punto')),
                ('codigo_qr', models.CharField(max_length=100, unique=True, verbose_name='Código QR')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Código QR',
                'verbose_name_plural': 'Códigos QR',
                'ordering': ['empresa', 'nombre'],
            },
        ),
    ]
